"""Providers module for router-maestro."""

from router_maestro.providers.anthropic import AnthropicProvider
from router_maestro.providers.base import (
    TIMEOUT_NON_STREAMING,
    TIMEOUT_STREAMING,
    BaseProvider,
    ChatRequest,
    ChatResponse,
    ChatStreamChunk,
    ContextWindowOption,
    Message,
    ModelInfo,
    ProviderError,
    ProviderFailureKind,
    ProviderFailureSignal,
    RequestOptionError,
    ResponsesRequest,
    ResponsesResponse,
    ResponsesStreamChunk,
    ResponseStatus,
    ResponsesToolCall,
    TerminalError,
    TerminalOutcome,
    TransportTermination,
    classify_upstream_status,
    client_cancelled_outcome,
    exception_outcome,
    finish_reason_for_outcome,
    resolve_terminal_outcome,
    unexpected_eof_outcome,
)
from router_maestro.providers.bindings import (
    COPILOT_ANTHROPIC_MESSAGES_BINDING,
    COPILOT_OPENAI_CHAT_BINDING,
    COPILOT_OPENAI_RESPONSES_BINDING,
    LEGACY_ANTHROPIC_MESSAGES_BINDING,
    LEGACY_OPENAI_CHAT_BINDING,
    LEGACY_OPENAI_RESPONSES_BINDING,
    OPENAI_COMPATIBLE_CHAT_BINDING,
    AttemptRequestContext,
    EndpointBinding,
    HttpExecutor,
    PreparedAttempt,
    ProviderDialect,
)
from router_maestro.providers.copilot import CopilotProvider
from router_maestro.providers.http_executor import ProviderHttpClientPool, SharedHttpExecutor
from router_maestro.providers.openai import OpenAIProvider
from router_maestro.providers.openai_base import OpenAIChatProvider
from router_maestro.providers.openai_compat import OpenAICompatibleProvider

__all__ = [
    # Constants
    "TIMEOUT_NON_STREAMING",
    "TIMEOUT_STREAMING",
    # Base classes
    "BaseProvider",
    "ProviderError",
    "ProviderFailureKind",
    "ProviderFailureSignal",
    "RequestOptionError",
    "ResponseStatus",
    "TerminalError",
    "TerminalOutcome",
    "TransportTermination",
    "resolve_terminal_outcome",
    "unexpected_eof_outcome",
    "Message",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamChunk",
    "ContextWindowOption",
    "classify_upstream_status",
    "client_cancelled_outcome",
    "exception_outcome",
    "finish_reason_for_outcome",
    "ModelInfo",
    "ResponsesRequest",
    "ResponsesResponse",
    "ResponsesStreamChunk",
    "ResponsesToolCall",
    "OpenAIChatProvider",
    "AttemptRequestContext",
    "EndpointBinding",
    "HttpExecutor",
    "PreparedAttempt",
    "ProviderDialect",
    "ProviderHttpClientPool",
    "SharedHttpExecutor",
    "LEGACY_OPENAI_CHAT_BINDING",
    "LEGACY_OPENAI_RESPONSES_BINDING",
    "LEGACY_ANTHROPIC_MESSAGES_BINDING",
    "COPILOT_ANTHROPIC_MESSAGES_BINDING",
    "COPILOT_OPENAI_CHAT_BINDING",
    "COPILOT_OPENAI_RESPONSES_BINDING",
    "OPENAI_COMPATIBLE_CHAT_BINDING",
    # Providers
    "CopilotProvider",
    "OpenAIProvider",
    "AnthropicProvider",
    "OpenAICompatibleProvider",
]
