"""Server schemas."""

from router_maestro.server.schemas.admin import (
    AuthListResponse,
    AuthProviderInfo,
    LoginRequest,
    ModelInfo,
    ModelsResponse,
    OAuthInitResponse,
    OAuthStatusResponse,
    PrioritiesResponse,
    PrioritiesUpdateRequest,
)
from router_maestro.server.schemas.openai import (
    ChatCompletionChoice,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    ChatCompletionChunkDelta,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionUsage,
    ChatMessage,
    ErrorDetail,
    ErrorResponse,
    ModelList,
    ModelObject,
)
from router_maestro.server.schemas.responses import (
    ResponsesDeltaEvent,
    ResponsesDoneEvent,
    ResponsesFunctionCallInput,
    ResponsesFunctionCallOutput,
    ResponsesFunctionTool,
    ResponsesInputMessage,
    ResponsesInputTextContent,
    ResponsesMessageOutput,
    ResponsesOutputText,
    ResponsesReasoningOutput,
    ResponsesRequest,
    ResponsesResponse,
    ResponsesStreamEvent,
    ResponsesToolChoiceFunction,
    ResponsesUsage,
)

__all__ = [
    # Admin schemas
    "AuthListResponse",
    "AuthProviderInfo",
    "LoginRequest",
    "ModelInfo",
    "ModelsResponse",
    "OAuthInitResponse",
    "OAuthStatusResponse",
    "PrioritiesResponse",
    "PrioritiesUpdateRequest",
    # OpenAI schemas
    "ChatCompletionChoice",
    "ChatCompletionChunk",
    "ChatCompletionChunkChoice",
    "ChatCompletionChunkDelta",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatCompletionUsage",
    "ChatMessage",
    "ErrorDetail",
    "ErrorResponse",
    "ModelList",
    "ModelObject",
    # Responses API schemas
    "ResponsesDeltaEvent",
    "ResponsesDoneEvent",
    "ResponsesFunctionCallInput",
    "ResponsesFunctionCallOutput",
    "ResponsesFunctionTool",
    "ResponsesInputMessage",
    "ResponsesInputTextContent",
    "ResponsesMessageOutput",
    "ResponsesOutputText",
    "ResponsesReasoningOutput",
    "ResponsesRequest",
    "ResponsesResponse",
    "ResponsesStreamEvent",
    "ResponsesToolChoiceFunction",
    "ResponsesUsage",
]
